{% set name = "johnnydep" %}
{% set version = "1.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/wimglenn/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 50892928392a511d43129ff05313687a00338289fd61e3ece53c014413bc6470

build:
  noarch: python
  number: 0
  entry_points:
    - johnnydep=johnnydep.cli:main
    - pipper=johnnydep.pipper:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=2.7
    - pip
  run:
    - python >=2.7
    - anytree
    - structlog
    - tabulate
    - wimpy
    - colorama
    - cachetools
    - distlib
    - oyaml
    - toml
    - pip
    - packaging >=17
    - wheel >=0.32.0
    - setuptools >=38.3
    - pkginfo >=1.4.2

test:
  imports:
    - johnnydep
  commands:
    - johnnydep --version

about:
  home: https://github.com/wimglenn/johnnydep
  license: MIT
  license_file: LICENSE
  summary: Display dependency tree of Python distribution
  dev_url: https://github.com/wimglenn/johnnydep

extra:
  recipe-maintainers:
    - ickc
