{% set name = "johnnydep" %}
{% set version = "1.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/johnnydep-{{ version }}.tar.gz
  sha256: 5ee4e716abea3a60e4b022be4f70d1e7991a2da6ed726ce307c22650a882d48a

build:
  entry_points:
    - johnnydep = johnnydep.cli:main
    - pipper = johnnydep.pipper:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - anytree
    - cachetools
    - colorama
    - distlib
    - oyaml
    - packaging >=17
    - pip
    - pkginfo >=1.4.2
    - python >=3.6
    - setuptools >=38.3
    - structlog
    - tabulate
    - toml
    - wheel >=0.32.0
    - wimpy

test:
  imports:
    - johnnydep
  commands:
    - pip check
    - johnnydep --help
    - pipper --help
  requires:
    - pip

about:
  home: https://github.com/wimglenn/johnnydep
  summary: Display dependency tree of Python distribution
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ickc
